<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://firebasestorage.googleapis.com/v0/b/debo-d791b.appspot.com/o/IMG_20181102_005811.JPG?alt=media&token=5a0ea1ab-7b0a-4c81-9058-0ffde6c2b4c1" alt="Mark Essien">
                        <h6>Bello gbadebo</h6>
                        <p>Full Stack Javascript Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/BelloGbadebo1" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Gbahdeyboh" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@gbahdeybohbello" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                           I am Bello Gbadebo by name, an 100lvl Electrical and Electronics Engineering student in the federal university of Agriculture Abeokuta and I'm very ethusiastic about everything technology.
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Node | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
